name: Build and Deploy Next.js App to Azure Web App

on:
  push:
    branches:
      - main  
  workflow_dispatch:

env:
  WEBAPP_NAME: "PortfolioJorisMathijssenApp"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.1
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: "20.x"
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Lint Code
        run: npm run lint

      - name: Run Tests
        run: npm test

      - name: Build the Project
        run: npm run build

      - name: List Directory After Build
        run: ls -la

      - name: List Build Directory Contents
        run: ls -la ./build

      - name: List Build Directory Recursively
        run: ls -laR ./build

      - name: Prepare Build Artifacts
        run: |
          mkdir -p ./build/standalone/
          # Adjust the copy command based on your build output
          cp -r build/.next ./build/standalone/          # If .next is inside build
          # OR
          # cp -r build ./build/standalone/             # If build is the output directory
          cp -r public ./build/standalone/
          cp package.json package-lock.json ./build/standalone/

      - name: List Build Directory Contents After Preparation
        run: ls -la ./build/standalone

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4.4.3
        with:
          name: build-artifacts
          path: ./build/standalone/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: ./build/standalone/

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          slot-name: "Production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./build/standalone/
